TomWhitwell/SlowMovie

- slowmovie.py
currently width is passed to `generate_frame` but height is not. both are used and it's working only since height is declared as a global before the first call
> pass both width and height to generate_frame

- e-paper/rpi/python/lib/waveshare_epd/epd7in5_V2.py
- e-paper/rpi/python/lib/waveshare_epd/epdconfig.py
After running a while (depending on update frequency) the program eventually crashes with a __to many open files__ error. This error is a direct consequence of the fix for the ```epd.sleep()``` functionality. The order of events that leads to this is as follows: 
1. The initial starting of the program initializes the EPD driver, this causes an instance of ```self.SPI = spidev.SpiDev()``` to be created. 
2. Every run of the program calls ```epd.init()```, which initializes the SPI interface with a call to ```self.SPI.open(0, 0)```
3. SlowMovie calls ```epd.sleep()``` to enter the low power mode
4. After the sleep duration calls ```epd.init()``` again, creating another call to ```self.SPI.open(0, 0)```. 
These repeated calls to the ```open()``` function accumulate open file handles that …
> fixes spidev "too many files" issue

- slowmovie.py
* Changes video_info function to return an dictionary.
* Get framerate and frame count in a more robust way from the ffmpeg 
probe. This method works for the mkv I was testing on.
* The dictionary returned from video_info now includes duration, setting 
up for future runtime estimates.
Hopefully equivalent to f450a90, baa0526, and 8f0c58a
> Add .mkv support

- slowmovie.py
This is something I previously implemented in `helloworld.py`. 
The first time a given video is scanned, the results are added to a dict. Then, if the same file is encountered again, the video info is retrieved from the dict rather than running ffprobe again, which can take a few seconds on slower devices.
This'll be particularly useful if a "random frames from folder" mode is added (this is what `helloworld.py` does).
> Remember video info for each video

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/help.md
- .github/ISSUE_TEMPLATE/informational.md
- .github/ISSUE_TEMPLATE/question.md
Inspired by #62 
1. adding comments so the instructions don't show in posted issues
2. adding `help` tag and issue template
* My thought is, until we have a Wiki or something, people are probably going to post issues asking for help with various problems. Without a help option, they'll probably just get labeled as bugs even when they're not.
* Maybe eventually we can use a Wiki for common problems and maybe even the new Discussions feature. Something we decide works well for this type of thing. Until then, I think this'll be good to have a place for this type of activity which we've seen to be common for this repo.
> Issue templates

- .github/CONTRIBUTING.md
Based on the flow we've kind of started I wanted to capture it as part of the contributing file. The basic idea is that for simple PRs at least one additional review (other than the PR author) are needed before merging in. This should make easy things like documentation and syntax updates quick to get approved and merged in. For larger updates that touch functionality we'll want to get more input and testing of the code. 
There are some settings in GitHub we can turn on to enforce this kind of flow but we'd need Tom to turn them on as only a full repo Admin has access to them. If it's in writing at least there aren't any surprises when something is merged in or not merged in depending on what it touches. 
Feel free to wordsmith this, it's just a jumping off point.
> Review Process Flow

- README.md
- slowmovie.py
I've been sitting on this one for a while because I didn't know if It'd be worth adding.
This adds a `--subtitles` argument that, when enabled, Looks for subtitle files matching the video's filename. Supported filetypes are SRT, SSA, and ASS. Any type supported by ffmpeg should work, but those seem to be the most common.
Embedded subtitle tracks *would* work, but it seems to take a lot longer to extract frames, so I've left that out.
Any thoughts?
> Subtitle Support

- slowmovie.py
I wanted to play some old Futurama episodes that happened to be in an AVI format and didn't feel like converting them. Looks like the existing code works with that format as long as it's listed as an allowed file type. 
```
python3 slowmovie.py -f "/home/pi/Videos/Futurama - The Luck of the Fryrish.S03.E10.avi" -s 200 -i 30
Update interval: 120
Frame increment: 30
Starting at frame 200
Playing 'Futurama - The Luck of the Fryrish.S03.E10.avi'
Video info: 33316 frames, 25.000fps, duration: 00:22:12
This video will take 1.53 day(s) to play.
```
> Add AVI File Type

- slowmovie.py
As suggested by @jschrempp, this enables logging for argparse errors.
```console
pi@pizero:~/SlowMovie $ ./slowmovie.py -f null.mp4
argument -f/--file: File 'null.mp4' does not exist
```
```
[2021-05-29 14:45:03,231] ERROR   : argument -f/--file: File 'null.mp4' does not exist
```
> Log argparse errors

- Install/install.sh
- README.md
I just tried this on a freshly-imaged card, works fine this way. Pip isn't really supposed to be run as root anyway. Everything goes in `~/.local/lib` instead. It does produce warnings like this:
```
The script omni-epd-test is installed in '/home/pi/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
...but this is already handled in `.profile`.
```shell
if [ -d "$HOME/.local/bin" ] ; then
PATH="$HOME/.local/bin:$PATH"
fi
```
I've also removed the "update setuptools" step. That doesn't seem to be necessary anymore.
> Run pip without sudo

- Install/install.sh
- Install/requirements.txt
- README.md
When running the `install.sh` file Python lib dependencies are not updated. It appears as though when installing from a git URL using pip it will not honor version updates in a setup.py or setup.cfg file. 
The fix for this is to use the `-U` flag to force updates of all dependencies to the latest version. This works great but one question before merging I have is if we want to start specifying specific versions within the `requirements.txt` file? Our requirements for these libraries are pretty minimal so it's unlikely updates will break things; however by specifying known working versions we are covering our bases as well. For Git URLs you can specify a tagged revision so for libs like `omni-epd` we can add `@v0.2.3` as part of the URL string.
Of course the downside to this is that we'll …
> Python Libs Update

- slowmovie.py
This sets the log level value for the Python global logger as well. This allows the console output to show messages from other modules (like Waveshare) that use logging. This won't affect the regular log file since that handler is for the SlowMovie logger only. 
Without this collecting logs from the other modules is basically impossible without modifying the code directly.
> Global logging

- Install/requirements.txt
Updates omni-epd to version 0.2.4. This fixes issues with the Waveshare 3.7in devices. This device is tested and working properly now.
> omni-epd 0.2.4

- Install/requirements.txt
Update to latest version of omni-epd. This includes fixes and tested support for two additional EPD types. 
* waveshare_epd.epd2in9
* waveshare_epd.epd5in83c
> omni-epd v0.2.5

- Install/requirements.txt
Fix for more picky dependency matching in newer versions of Raspberry Pi OS
> Waveshare URL fix

- README.md
This change updates the README waveshare-epd driver installation in the manual instructions to match the install.txt.
Relates to https://github.com/TomWhitwell/SlowMovie/pull/104
> Update waveshare driver URL to match install.txt

- README.md
- slowmovie.py
There are currently a lot of arguments that can be set in either the config file or passed via the command line. This doesn't change any of them in any way, but it does re-organize the help menu when using `-h`. Using argument groups, options are put into sections that help the user sort through which they may need in a better fashion. Instead of everything being listed in one lump it's now easier to tell which are for specifying the file to load, settings for frame updates, and EPD control. 
Reorganized `-h` output now looks like this: 
```
usage: slowmovie.py [-h] [-f FILE] [-D DIRECTORY] [-l] [-R]
[-o {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [-r] [-d DELAY]
[-i INCREMENT] [-s START] [-S | -t] [-e EPD] [-c CONTRAST]
[-C]
optional arguments:
-h, --help            show this help message and …
```
> Help Menu Groups

- slowmovie.py
This will solve the problem found in #111 where hidden files that weren't actually video files were being included in the file listing. `os.listdir()` returns hidden system files that start with a dot (`.`). This fix will filter them out at the time the file list is being generated. In the issue referenced above files such as `._test.mp4` were being included. I imagine this happens when entire directories are copied from other computers (Mac, Windows) that have generated things like thumbnails that include the full file name. 
I tried a few different ways of doing this, including using the `glob` package; but this seemed the most efficient. glob returned the absolute path to the files instead of just the filename, which would have created a bunch of downstream problems as we're expecting …
> Filter out hidden files

- Install/requirements.txt
This will bump the omni-epd version to 0.3.0. This version includes support for IT8951 devices as well as the ability to use `inky.auto` to auto detect Inky displays. Numerous other bug fixes as well that can be found in [the Changelog](https://github.com/robweber/omni-epd/blob/main/CHANGELOG.md).
> omni-epd to 0.3.0

- Install/requirements.txt
This will update omni-epd to the latest version. The full changelog is below but the big change in this revision is enhancements to the [dithering options](https://github.com/robweber/omni-epd/wiki/Image-Dithering-Options). There are more and they work faster. 
- `omni_epd.mock` can now set both the width and height values within the `.ini` file. Thanks @missionfloyd
- `omni_epd.mock` device now returns a palette filter when using the color mode. Previously this returned only b/w and resulted in image processing enhancements resulting in a black and white only image, even when color was selected. Hardcoded palette based on web safe colors.
- Waveshare device `epd2in13_V2` should use the alternate clear method which requires a color parameter. Thanks @ThatIsAPseudo for pointing this out
- …
> update omni-epd to version 0.3.1

- Install/requirements.txt
This updates omni-epd to version 0.3.2 and makes the Pillow version equal to, or greater than, version 9.1.0. 
The [big changes](https://github.com/robweber/omni-epd/releases/tag/v0.3.2) with omni-epd are the addition of some new Waveshare devices and a bump in Pillow to 9.1.0 or greater. This translates to why the Pillow bump here as well. The [Pillow release notes](https://pillow.readthedocs.io/en/latest/releasenotes/9.1.0.html#constants) explain that some of the constants in that library have migrated and the old ones removed in a later release. This makes sure everything is on the same minimum version.
> Update omni-epd and Pillow versions

- Install/install.sh
- README.md
- slowmovie.service.template
With newer versions of the Raspberry Pi OS you can't count on the default `pi` user being the path for the home folder anymore. This PR attempts to modify the install procedure and the install script to insert the current user name in places where a full path is needed. For the `install.sh` script this is pretty simple. I just replaced any hardcoded paths from `/home/pi` to `/home/$USER`. 
The one piece that was a little tricky was the `slowmovie.service` file. This needed to be updated on the fly rather than a static file with hardcoded paths. I utilized the [envsubst](https://manpages.debian.org/unstable/gettext-base/envsubst.1.en.html) shell function to generate the service file from a template and then move that file to the correct location. 
This is a 1:1 replacement for the current …
> Dynamic Install Path

- README.md
- slowmovie.py
As suggested by @TomWhitwell, this adds an option (`--fullscreen` or `-F`) to crop the image to the center, eliminating borders.
> Crop out borders

- Install/install.sh
These should fix both #140  and #141. 
For the first one the service install process was not working properly as it wasn't generating the service file from the template as expected.  Some reconfiguring of the service install process was done to fix this. I added a `copy_service_file` function to keep all this code in the same spot. The `install_slowmovie` function now calls `install_service` directly when it notices the service is installed during an upgrade. `install_service` now branches to either do a new service install or an upgraded service (if necessary). 
For the second bug I actually found this while trying to fix the first one. When selecting "no" to the service install question the entire script was just closing out instead of continuing properly. I played around with …
> Service install Fixes

- Install/requirements.txt
Bumps omni-epd branch to current version. Summary of changes below. 
- `palette_filter` advanced option now supports [color names](https://github.com/python-pillow/Pillow/blob/e3cb4bb8e00fcaf4c3e0783f7c02e51372595659/src/PIL/ImageColor.py#L153-L305) or hex values in addition to RGB colors. Thanks missionfloyd
- IT8951 devices now support `gray16` mode for grayscale
- [Waveshare 10.3 IT8951](https://www.waveshare.com/10.3inch-e-paper-hat.htm) device marked as tested. Thanks simonjowett
- added link to [pycasso](https://github.com/jezs00/pycasso) in the README. Thanks jezs00
- new displays, [Waveshare 7.3in 7 Color](https://www.waveshare.com/7.3inch-e-paper-hat-f.htm) - thanks evelyndooley, [Waveshare 2.13in V3](https://www.waveshare.com/2.13inch-e-paper-hat.htm)
> updated omni-epd to version 0.3.4

- README.md
Until the issues with upstream projects for Bookworm can be worked out (namely Waveshare) this disclaimer will let new installs know they should use Bullseye for now.
> Bookworm Disclaimer
